# Generated by Django 3.2.16 on 2022-12-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField()),
                ('author', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField()),
                ('title', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=512)),
            ],
        ),
    ]
